spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false


# spring.datasource.testWhileIdle=true
# spring.jpa.defer-datasource-initialization=true
# postgresql://postgres:RmWmrcSxLFXIQMyfOmsaijpyVLtXBfUO@postgres:railway:internal:5432/railway: