spring:
  datasource:
    url: jdbc:postgresql://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        transaction:
          jta:
            platform: true
        ddl-auto: create
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false


# spring.datasource.testWhileIdle=true
# spring.jpa.defer-datasource-initialization=true
# postgresql://postgres:RmWmrcSxLFXIQMyfOmsaijpyVLtXBfUO@postgres:railway:internal:5432/railway: